#!/bin/sh

CODESPACE_IP_ADDR="0.0.0.0";
CODESPACE_ORIGIN=${hostname};
CODESPACE_PORT="8080";

#echo ".......export CODESPACE_PORT=${CODESPACE_PORT}; jupyter lab --port=${CODESPACE_PORT} --ip=${CODESPACE_PORT} --ServerApp.disable_check_xsrf=True --ServerApp.allow_origin=\'*\'
#echo ".......export CODESPACE_PORT=${CODESPACE_PORT}; jupyter lab --port=${CODESPACE_PORT} --ip=${CODESPACE_IP_ADDR} --ServerApp.disable_check_xsrf=True --ServerApp.allow_origin=\'${CODESPACE_ORIGIN}\' "
#export CODESPACE_PORT=${CODESPACE_PORT}; jupyter lab --port=${CODESPACE_PORT} --ip=${CODESPACE_IP_ADDR} --ServerApp.disable_check_xsrf=True --ServerApp.allow_origin=\'${CODESPACE_ORIGIN}\'

echo ".......export CODESPACE_PORT=${CODESPACE_PORT}; jupyter lab --port=${CODESPACE_PORT} --ip=${CODESPACE_IP_ADDR} --ServerApp.disable_check_xsrf=True --ServerApp.allow_origin=\'*\' "
export CODESPACE_PORT=${CODESPACE_PORT}; jupyter lab --port=${CODESPACE_PORT} --ip=${CODESPACE_IP_ADDR} --ServerApp.disable_check_xsrf=True --ServerApp.allow_origin=\'*\'
